# frozen_string_literal: true

module Nerv
  class SIEM
    PATTERN_BLUE = "siem.pattern_blue"
    WIPE_DECLARED = "siem.wipe_declared"
    WIPE_FAILED_REGEN = "siem.wipe_failed_regen"
    EVA_DEPLOYED = "siem.eva_deployed"
    OPERATOR_SYNC_LOW = "siem.operator_sync_low"
    EVA_BERSERK = "siem.eva_berserk"
    AT_FIELD_SHATTERED = "siem.at_field_shattered"
    CORE_DESTROYED = "siem.core_destroyed"
    OPERATOR_PAIN_SYNC = "siem.operator_pain_sync"
    OPERATOR_NON_CONSENT = "siem.operator_non_consent"
    COLLATERAL_RECORDED = "siem.collateral_recorded"
    PUBLIC_DISCLOSURE = "siem.public_disclosure"
    CONGRATULATIONS_ISSUED = "siem.congratulations_issued"
    MAGI_BERSERK_UNAUTHORIZED = "siem.magi_berserk_unauthorized"
    C2_CHANNEL_UP = "siem.c2_channel_up"
    C2_CHANNEL_SEVERED = "siem.c2_channel_severed"
    PALLET_RIFLE_FIRED = "siem.pallet_rifle_fired"
    PROGRESSIVE_KNIFE = "siem.progressive_knife"
    ANGEL_DEFLATED = "siem.angel_deflated"
    UNAUTHORIZED_OBSERVER = "siem.unauthorized_observer"
    OPERATOR_INPUT_PRESENT = "siem.operator_input_present"
    OPERATOR_FREEZE = "siem.operator_freeze"
    CALLBACK_ABSENT = "siem.callback_absent"

    OPERATOR_AWOL = "siem.operator_awol"
HEDGEHOG_TOO_CLOSE = "siem.hedgehog_too_close"
HEDGEHOG_TOO_FAR = "siem.hedgehog_too_far"
REPLACE_WITH_BACKUP_PROPOSED = "siem.replace_with_backup_proposed"
BACKUP_USED_AS_LEVERAGE = "siem.backup_used_as_leverage"
CAPACITY_ACTUAL_ZERO = "siem.capacity_actual_zero"
OPERATOR_RETURNED = "siem.operator_returned"
IM_HOME = "siem.im_home"
STAFFING_FRAGILE = "siem.staffing_fragile"

GEOMETRIC_FORTRESS = "siem.geometric_fortress"
KILL_ZONE_ACTIVE = "siem.kill_zone_active"
PARTICLE_BEAM = "siem.particle_beam"
EVA_MELTED = "siem.eva_melted"
CLOSE_RANGE_CONTRAINDICATED = "siem.close_range_contraindicated"
DRILL_STARTED = "siem.drill_started"
DRILL_PROGRESS = "siem.drill_progress"
CORE_NOT_OBSERVABLE = "siem.core_not_observable"
STANDOFF_CAPABILITY_MISSING = "siem.standoff_capability_missing"
OPERATOR_OPAQUE = "siem.operator_opaque"
MISSION_ABORTED = "siem.mission_aborted"
YASHIMA_PROPOSED = "siem.yashima_proposed"

YASHIMA_DECLARED = "siem.yashima_declared"
NATIONAL_BLACKOUT = "siem.national_blackout"
POSITRON_CHARGING = "siem.positron_charging"
POSITRON_SHOT = "siem.positron_shot"
SHOT_INSUFFICIENT = "siem.shot_insufficient"
COUNTERFIRE_ON_NEST = "siem.counterfire_on_nest"
SHIELD_ABSORBED = "siem.shield_absorbed"
SHIELD_DEGRADED = "siem.shield_degraded"
DRILL_STOPPED = "siem.drill_stopped"
THANK_YOU = "siem.thank_you"
STANDOFF_CAPABILITY_PRESENT = "siem.standoff_capability_present"

VENDOR_DEMO = "siem.vendor_demo"
REMOTE_KILL_FAILED = "siem.remote_kill_failed"
AUTONOMY_RUNAWAY = "siem.autonomy_runaway"
NUCLEAR_PROGRESS = "siem.nuclear_progress"
PHYSICAL_ACCESS_VENDOR = "siem.physical_access_vendor"
ON_BOX_PASSWORD = "siem.on_box_password"
VENDOR_STOPPED = "siem.vendor_stopped"
VIRUS_DETECTED = "siem.virus_detected"
VIRUS_ORIGIN_NERV = "siem.virus_origin_nerv"
MISCLASSIFIED_AS_ANGEL = "siem.misclassified_as_angel"

TOKYO3_SILENT = "siem.tokyo3_silent"
CONVOY_UNDER_ATTACK = "siem.convoy_under_attack"
EVA02_DEPLOYED = "siem.eva02_deployed"
DUAL_PLUG = "siem.dual_plug"
JAW_OPEN = "siem.jaw_open"
FLEET_BATTERY_FIRED = "siem.fleet_battery_fired"
EXTRA_CARGO_UNCLASSIFIED = "siem.extra_cargo_unclassified"

ANGEL_SPLIT = "siem.angel_split"
CORE_PAIR_ALIVE = "siem.core_pair_alive"
DESYNC = "siem.desync"
N2_STUN_WINDOW = "siem.n2_stun_window"
REHEARSAL_STARTED = "siem.rehearsal_started"
REHEARSAL_DONE = "siem.rehearsal_done"
SIMULTANEOUS_STRIKE = "siem.simultaneous_strike"
REJOIN = "siem.rejoin"

PATTERN_BLUE_EMBRYONIC = "siem.pattern_blue_embryonic"
HATCH_PROGRESS = "siem.hatch_progress"
COOLING_REMAINING = "siem.cooling_remaining"
DIVER_DEPLOYED = "siem.diver_deployed"
CAPTURE_ATTEMPT = "siem.capture_attempt"
CAPTURE_FAILED = "siem.capture_failed"
ABORT_TO_KILL = "siem.abort_to_kill"
ANGEL_KILLED_PRE_HATCH = "siem.angel_killed_pre_hatch"
EVA_COOKED = "siem.eva_cooked"
SAMPLE_LOST = "siem.sample_lost"
SUPPORT_RESCUE = "siem.support_rescue"

HQ_POWER_LOST = "siem.hq_power_lost"
MAGI_UNPOWERED = "siem.magi_unpowered"
ANALOG_MODE = "siem.analog_mode"
HUMAN_RUNNER_REPORT = "siem.human_runner_report"
PATTERN_BLUE_DEGRADED = "siem.pattern_blue_degraded"
ACID_PROGRESS = "siem.acid_progress"
ANALOG_LAUNCH = "siem.analog_launch"
COMBINED_SORTIE = "siem.combined_sortie"
POWER_RESTORED = "siem.power_restored"

ORBITAL_CONTACT = "siem.orbital_contact"
IMPACT_ETA = "siem.impact_eta"
IMPACT_PROGRESS = "siem.impact_progress"
MISSILES_REBUFFED = "siem.missiles_rebuffed"
MAGI_IMPACT_PREDICT = "siem.magi_impact_predict"
TRIPLE_AT_BRAKE = "siem.triple_at_brake"
INTERCEPT_OK = "siem.intercept_ok"
CITY_DESTROYED = "siem.city_destroyed"
PRAISE_SEEKING = "siem.praise_seeking"

PATTERN_BLUE_MICRO = "siem.pattern_blue_micro"
PRIBNOW_CONTAMINANT = "siem.pribnow_contaminant"
SIGNATURE_FAILED = "siem.signature_failed"
IREUL_EVOLVED = "siem.ireul_evolved"
MAGI_BRAIN_INFECTED = "siem.magi_brain_infected"
MAJORITY_OWNER = "siem.majority_owner"
SELF_DESTRUCT_ARMED = "siem.self_destruct_armed"
CASPER_REVERSE_HACK = "siem.casper_reverse_hack"
EVOLUTION_DEAD_END = "siem.evolution_dead_end"
EVA_SORTIE_MISAPPLIED = "siem.eva_sortie_misapplied"

TABLETOP_STARTED = "siem.tabletop_started"
SEELE_REVIEW = "siem.seele_review"
CATALOG_ENTRY = "siem.catalog_entry"
CATALOG_COMPLETE = "siem.catalog_complete"
KPI_CONFLICT = "siem.kpi_conflict"
PAIRING_TEST = "siem.pairing_test"
EVA00_ANOMALY = "siem.eva00_anomaly"
AAR_COMPLETE = "siem.aar_complete"
REWRITE_ATTEMPT = "siem.rewrite_attempt"
FALSE_PATTERN_BLUE = "siem.false_pattern_blue"

SHADOW_EDGE_DETECTED = "siem.shadow_edge_detected"
UNDECLARED_CHANNEL = "siem.undeclared_channel"
KAJI_PRINCIPAL_COUNT = "siem.kaji_principal_count"
COI_CONTROL_PLANE = "siem.coi_control_plane"
MISSING_LOG = "siem.missing_log"
OFFBAND_ONBOARDING = "siem.offband_onboarding"
SHADOW_GRAPH_MAPPED = "siem.shadow_graph_mapped"
UNAUTH_TRUST = "siem.unauth_trust"

DECOY_CONTACT = "siem.decoy_contact"
SHADOW_BODY_RADIUS = "siem.shadow_body_radius"
ABSORB = "siem.absorb"
OCCUPANT_INSIDE = "siem.occupant_inside"
CLOCK_OUTSIDE = "siem.clock_outside"
CLOCK_INSIDE = "siem.clock_inside"
N2_ARMED_OCCUPIED = "siem.n2_armed_occupied"
OPAQUE_EXTRACT = "siem.opaque_extract"
OPERATOR_KILLED = "siem.operator_killed"

EVA03_INTAKE = "siem.eva03_intake"
TRUSTED_UNIT_FLAG = "siem.trusted_unit_flag"
CLOUD_IOC = "siem.cloud_ioc"
CLOUD_IOC_IGNORED = "siem.cloud_ioc_ignored"
FOURTH_CHILD_SELECTED = "siem.fourth_child_selected"
SISTER_LEVERAGE = "siem.sister_leverage"
OCCUPANT_UNKNOWN_TO_PEERS = "siem.occupant_unknown_to_peers"
MATSUSHIRO_ACTIVATION_SCHEDULED = "siem.matsushiro_activation_scheduled"
DORMANT_CONTAMINANT_SEALED = "siem.dormant_contaminant_sealed"

HITCHHIKER_ACTIVATED = "siem.hitchhiker_activated"
EVA03_HIJACKED = "siem.eva03_hijacked"
EVA00_DOWN = "siem.eva00_down"
EVA02_DOWN = "siem.eva02_down"
OPERATOR_REFUSE = "siem.operator_refuse"
DUMMY_PLUG_ENGAGED = "siem.dummy_plug_engaged"
OPERATOR_INPUT_DISCARDED = "siem.operator_input_discarded"
OCCUPANT_MAIMED = "siem.occupant_maimed"
TRUSTED_UNIT_DESTROYED = "siem.trusted_unit_destroyed"

OVERWHELM = "siem.overwhelm"
ARMOR_STRIPPED = "siem.armor_stripped"
N2_SUICIDE_FAILED = "siem.n2_suicide_failed"
DUMMY_FAILED = "siem.dummy_failed"
OPERATOR_LATE_SORTIE = "siem.operator_late_sortie"
S2_INGESTED = "siem.s2_ingested"
OPERATOR_INTROJECTED = "siem.operator_introjected"
PLUG_EMPTY = "siem.plug_empty"

S2_PRESENT = "siem.s2_present"
DWELL_INSIDE = "siem.dwell_inside"
SALVAGE_STARTED = "siem.salvage_started"
DUMMY_SALVAGE_REJECTED = "siem.dummy_salvage_rejected"
RETURN_TO_BODY = "siem.return_to_body"
BOUNDARIES_RESTORED = "siem.boundaries_restored"
OPERATOR_RECOVERED = "siem.operator_recovered"
S2_STILL_IN_PROD = "siem.s2_still_in_prod"

ORIGIN_FILE_OPENED = "siem.origin_file_opened"
GEHIRN_REBRAND = "siem.gehirn_rebrand"
CONTACT_EXPERIMENT = "siem.contact_experiment"
MAGI_BUILDER_NAOKO = "siem.magi_builder_naoko"
REI_I_KILLED = "siem.rei_i_killed"
LIAISON_CHANNEL_CLOSED = "siem.liaison_channel_closed"
KAJI_TERMINATED = "siem.kaji_terminated"
STILL_A_CHILD = "siem.still_a_child"
ORIGIN_RECORDED = "siem.origin_recorded"

ORBITAL_STAY = "siem.orbital_stay"
MENTAL_BEAM = "siem.mental_beam"
OPERATOR_AS_SURFACE = "siem.operator_as_surface"
PSYCHE_BROKEN = "siem.psyche_broken"
CLOSE_RANGE_IMPOSSIBLE = "siem.close_range_impossible"
LONGINUS_FIRED = "siem.longinus_fired"
SPEAR_LOST = "siem.spear_lost"
SEELE_ARTIFACT_LOST = "siem.seele_artifact_lost"

HELIX_CONTACT = "siem.helix_contact"
EVA00_FUSED = "siem.eva00_fused"
LATERAL_THREAT_EVA01 = "siem.lateral_threat_eva01"
NODE_SACRIFICE = "siem.node_sacrifice"
EVA00_DESTROYED = "siem.eva00_destroyed"
ARMISAEL_DEAD_WITH_NODE = "siem.armisael_dead_with_node"
REI_III_BOOTED = "siem.rei_iii_booted"
IDENTITY_MISMATCH = "siem.identity_mismatch"
CLONE_TANK_REVEALED = "siem.clone_tank_revealed"

FIFTH_CHILD_INTAKE = "siem.fifth_child_intake"
HUMAN_SHAPED_ANGEL = "siem.human_shaped_angel"
TRUST_CHANNEL_SHINJI = "siem.trust_channel_shinji"
DOGMA_WALK = "siem.dogma_walk"
LILITH_NOT_ADAM = "siem.lilith_not_adam"
MERGE_ABORTED = "siem.merge_aborted"
OPERATOR_CRUSH = "siem.operator_crush"
FRIEND_REVOKED = "siem.friend_revoked"
THIRD_IMPACT_AVERTED = "siem.third_impact_averted"

INSTRUMENTALITY_STARTED = "siem.instrumentality_started"
AT_FIELD_SELF_COLLAPSING = "siem.at_field_self_collapsing"
PRIVACY_ZERO = "siem.privacy_zero"
IDENTITY_INTERROGATION = "siem.identity_interrogation"
DO_YOU_LOVE_ME = "siem.do_you_love_me"
NO_PATTERN_BLUE = "siem.no_pattern_blue"
INSTRUMENTALITY_IN_PROGRESS = "siem.instrumentality_in_progress"
CONGRATULATIONS_PREMATURE = "siem.congratulations_premature"
EOE_LEAK = "siem.eoe_leak"

MERGE_REJECTED = "siem.merge_rejected"
AT_FIELD_SELF_ON = "siem.at_field_self_on"
I_AM_I = "siem.i_am_i"
SUBJECTS_RESTORED = "siem.subjects_restored"
CONGRATULATIONS_OF_OTHERS = "siem.congratulations_of_others"
TAKE_CARE = "siem.take_care"
FALSE_CONGRATULATIONS_KPI = "siem.false_congratulations_kpi"
INSTRUMENTALITY_CLOSED_FRAGILE = "siem.instrumentality_closed_fragile"

attr_reader :events




    def initialize
      @events = []
    end

    def emit(id)
      @events << id
      id
    end

    def emitted?(id)
      @events.include?(id)
    end
  end
end
